name: Train and deploy model

on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML job
      run: az ml job create --file src/job.yml --stream --resource-group <rg-name> --workspace-name <ws-name>

  production:
    runs-on: ubuntu-latest
    needs: experiment
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure ML job
      run: az ml job create --file src/job-prod.yml --stream --resource-group <rg-name> --workspace-name <ws-name>

